spring:
  profiles:
    active: chaos-monkey
  application:
    name: order-service
  threads:
    virtual:
      enabled: true

  boot:
    admin:
      client:
        url: http://localhost:8080  # adres serwera Spring Boot Admin

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_database
    username: postgres_admin
    password: postgres_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8102

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    chaosmonkey:
      enabled: true

  # observation documentation
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    export:
      prometheus:
        enabled: true

# https://codecentric.github.io/chaos-monkey-spring-boot/latest/#configuration
chaos:
  monkey:
    enabled: true # or just use chaos-monkey profile
    watcher:
#      restController: true
      restTemplate: true
      # There is no such property :D
#      restClient: true
      component: false
      service: false
      repository: false
    assaults:
      level: 2
      deterministic: false # this and above means: every 2 request
      latencyActive: true
      latencyRangeStart: 1000
      latencyRangeEnd: 3000

      exceptionsActive: true
      exception:
        type: java.lang.IllegalStateException
        arguments:
          - type: java.lang.String
            value: "monkey broke prod!"
